---
- name: install software
  hosts: ubuntu
  vars: 
  package_list:
    - nginx
    - default-jdk
    - python3.10
  tasks:
    - name: installation
      apt:
        name: "{{ item }}" 
        state: present
        update_cache: yes
      loop: "{{ package_list }}" 
