---
- name: Run uptime command on remote server
  hosts: all
  tasks: 
    - name: execute uptime command
      command: uptime
      register: uptime_output

    - name: print the output
      debug: 
        var: uptime_output.stdout

